### ISSUE TITLE
Request: admin access for origami-core

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/o-load#4]
Could the Origami-Core GitHub team have admin access to the repository? We try and ensure that components have the same labels for GitHub issues etc.

**Comment by chee** [comment]
![screenshot showing that origami has admin access](https://user-images.githubusercontent.com/178266/73600499-c26b5f80-4548-11ea-8f5a-e19d0665c5ce.png)

Looks like this has happened at some point!
